language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y make gcc libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev apt-file
script:
  - apt-file update
  - apt-file search sdl2-config
  - make -j2 VERBOSE=1
